apiVersion: v1
kind: ConfigMap
metadata:
  name: student-marketplace-config
  namespace: student-marketplace
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: student_marketplace
  DB_USER: marketplace_user
  REDIS_URL: redis://redis:6379
  AUTH_API_URL: http://auth-service:5002/api/auth
  PRODUCT_SERVICE_URL: http://product-service:5001/api
